blank_issues_enabled: false
contact_links:
  - name: Quick Feedback Form
    url: https://forms.gle/rPSh6xeeSUbngAbu7
    about: For quick feedback without creating a GitHub issue
  - name: HyperFocache Website
    url: https://hyperfocache.com
    about: Visit the main application
  - name: Documentation Request
    url: https://forms.gle/rPSh6xeeSUbngAbu7
    about: Request documentation or guides